name: Auto PR from Dev to Main

on:
  push:
    branches:
      - dev

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: dev
          destination_branch: main
          pr_title: "Auto PR: Merge Dev into Main"
          pr_body: "This PR was automatically created to merge changes from dev to main."
          pr_draft: false
